export const ROUTES = {
  home: '/',
  batches: '/batches',
  batchDetail: (slug: string) => `/batches/${slug}`,
  apply: (slug: string) => `/apply/${slug}`,
  confirmation: '/confirmation',
  waitlist: '/waitlist',
  terms: '/terms-and-conditions',
  privacy: '/privacy-policy',
  cancellationRefund: '/cancellation-and-refund',
  shipping: '/shipping-and-exchange',
  contact: '/contact-us',
  admin: '/admin',
  adminAffiliates: '/admin/affiliates',
  adminLogin: '/admin/login',
} as const
