export const ROUTES = {
  home: '/',
  batches: '/batches',
  batchDetail: (slug: string) => `/batches/${slug}`,
  apply: (slug: string) => `/apply/${slug}`,
  confirmation: '/confirmation',
  waitlist: '/waitlist',
  terms: '/terms-and-conditions',
  privacy: '/privacy-policy',
  cancellationRefund: '/cancellation-and-refund',
  shipping: '/shipping-and-exchange',
  contact: '/contact-us',
  admin: '/admin',
  adminBatches: '/admin/batches',
  adminBatchDepartures: (slug: string) => `/admin/batches/${slug}`,
  adminApplicant: (id: string) => `/admin/applicants/${id}`,
  adminWaitlist: '/admin/waitlist',
  adminAffiliates: '/admin/affiliates',
  adminLogin: '/admin/login',
  account: '/account',
  accountLogin: '/account/login',
  accountProfile: '/account/profile',
} as const
