export const ROUTES = {
  home: '/',
  batches: '/batches',
  batchDetail: (slug: string) => `/batches/${slug}`,
  apply: (slug: string) => `/apply/${slug}`,
  confirmation: '/confirmation',
  waitlist: '/waitlist',
  terms: '/terms-and-conditions',
  privacy: '/privacy-policy',
  cancellationRefund: '/cancellation-and-refund',
  shipping: '/shipping-and-exchange',
  contact: '/contact-us',
  admin: '/admin',
  adminBatches: '/admin/batches',
  adminBatchDepartures: (slug: string) => `/admin/batches/${slug}`,
  adminApplicant: (id: string) => `/admin/applicants/${id}`,
  adminWaitlist: '/admin/waitlist',
  adminAffiliates: '/admin/affiliates',
  adminLogin: '/admin/login',
  account: '/account',
  accountLogin: '/account/login',
  accountSignup: '/account/signup',
  accountForgotPassword: '/account/forgot-password',
  accountResetPassword: '/account/reset-password',
  accountProfile: '/account/profile',
  accountSettings: '/account/settings',
  accountPayments: '/account/payments',
  partner: '/partner',
  partnerProfile: '/partner/profile',
  partnerSettings: '/partner/settings',
  partnerLogin: '/partner/login',
  partnerSignup: '/partner/signup',
  partnerForgotPassword: '/partner/forgot-password',
  partnerResetPassword: '/partner/reset-password',
  authCallback: '/auth/callback',
} as const
